# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

def make_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("lrs_api", "Tenant")
    db_alias = schema_editor.connection.alias
    tenant = Tenant.objects.using(db_alias).get_or_create(name="Default initial tenant")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('verb', models.CharField(db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lrs_api.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lrs_api.Tenant'),
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lrs_api.User'),
        ),
        migrations.RunPython(make_default_tenant),
    ]
