# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lrs_api.User'),
        ),
    ]
