# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_api', '0002_auto_20170320_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
