# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_api', '0003_auto_20170324_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClientWithScopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_scopes', models.CharField(max_length=200)),
                ('app_pk', models.IntegerField(db_index=True)),
            ],
        ),
    ]
